// Define COLOR_MAP to be used by Slack. 'good' is green, 'danger' is red
def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]
pipeline {
    agent any

    environment {
        // Define variables on settings.xml file, refer to Nexus repo names and Jenkins credential name
        cluster = 'vproprod'
        service ='vproappprodsvc'

    }
    stages {
        stage("Deploy to Prod ECS") {
            steps {
                withAWS(credentials: 'awsecrcreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
            }
        }
    }

// Post stage execution, will run regardless of build status
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#vprofile',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}. \n More info at: ${env.BUILD_URL}"
        }
    }

}